// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/store/network/network.proto

package network

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	change "github.com/onosproject/onos-config/pkg/store/change"
	github_com_onosproject_onos_config_pkg_store_request "github.com/onosproject/onos-config/pkg/store/request"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Status is the status of a configuration object
type Status int32

const (
	// PENDING indicates the configuration is waiting to be applied
	Status_PENDING Status = 0
	// APPLYING indicates the configuration is in the process of being applied
	Status_APPLYING Status = 1
	// SUCCEEDED indicates the configuration was applied successfully
	Status_SUCCEEDED Status = 2
	// FAILED indicates the configuration failed
	Status_FAILED Status = 3
)

var Status_name = map[int32]string{
	0: "PENDING",
	1: "APPLYING",
	2: "SUCCEEDED",
	3: "FAILED",
}

var Status_value = map[string]int32{
	"PENDING":   0,
	"APPLYING":  1,
	"SUCCEEDED": 2,
	"FAILED":    3,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f93f65a36c7c529a, []int{0}
}

// Reason is a failure reason
type Reason int32

const (
	// ERROR indicates an error occurred
	Reason_ERROR Reason = 0
	// UNAVAILABLE indicates the device was unavailable
	Reason_UNAVAILABLE Reason = 1
)

var Reason_name = map[int32]string{
	0: "ERROR",
	1: "UNAVAILABLE",
}

var Reason_value = map[string]int32{
	"ERROR":       0,
	"UNAVAILABLE": 1,
}

func (x Reason) String() string {
	return proto.EnumName(Reason_name, int32(x))
}

func (Reason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f93f65a36c7c529a, []int{1}
}

// NetworkConfig specifies the configuration for a network change
type NetworkConfig struct {
	// id is the ID of the configuration
	ID        ID                                                      `protobuf:"bytes,1,opt,name=id,proto3,casttype=ID" json:"id,omitempty"`
	RequestID github_com_onosproject_onos_config_pkg_store_request.ID `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3,casttype=github.com/onosproject/onos-config/pkg/store/request.ID" json:"request_id,omitempty"`
	// revision is the configuration revision number
	Revision Revision `protobuf:"varint,3,opt,name=revision,proto3,casttype=Revision" json:"revision,omitempty"`
	// status is the current status of the configuration
	Status Status `protobuf:"varint,4,opt,name=status,proto3,enum=onos.config.network.Status" json:"status,omitempty"`
	// reason indicates the reason the configuration failed
	Reason Reason `protobuf:"varint,5,opt,name=reason,proto3,enum=onos.config.network.Reason" json:"reason,omitempty"`
	// message is an optional status message
	Message string `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	// created is the time at which the configuration was created
	Created time.Time `protobuf:"bytes,7,opt,name=created,proto3,stdtime" json:"created"`
	// updated is the time at which the configuration was last updated
	Updated time.Time `protobuf:"bytes,8,opt,name=updated,proto3,stdtime" json:"updated"`
	// changes is a set of changes to apply
	Changes []*change.Change `protobuf:"bytes,9,rep,name=changes,proto3" json:"changes,omitempty"`
}

func (m *NetworkConfig) Reset()         { *m = NetworkConfig{} }
func (m *NetworkConfig) String() string { return proto.CompactTextString(m) }
func (*NetworkConfig) ProtoMessage()    {}
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_f93f65a36c7c529a, []int{0}
}
func (m *NetworkConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NetworkConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NetworkConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NetworkConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkConfig.Merge(m, src)
}
func (m *NetworkConfig) XXX_Size() int {
	return m.Size()
}
func (m *NetworkConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkConfig.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkConfig proto.InternalMessageInfo

func (m *NetworkConfig) GetID() ID {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *NetworkConfig) GetRequestID() github_com_onosproject_onos_config_pkg_store_request.ID {
	if m != nil {
		return m.RequestID
	}
	return 0
}

func (m *NetworkConfig) GetRevision() Revision {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *NetworkConfig) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_PENDING
}

func (m *NetworkConfig) GetReason() Reason {
	if m != nil {
		return m.Reason
	}
	return Reason_ERROR
}

func (m *NetworkConfig) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *NetworkConfig) GetCreated() time.Time {
	if m != nil {
		return m.Created
	}
	return time.Time{}
}

func (m *NetworkConfig) GetUpdated() time.Time {
	if m != nil {
		return m.Updated
	}
	return time.Time{}
}

func (m *NetworkConfig) GetChanges() []*change.Change {
	if m != nil {
		return m.Changes
	}
	return nil
}

func init() {
	proto.RegisterEnum("onos.config.network.Status", Status_name, Status_value)
	proto.RegisterEnum("onos.config.network.Reason", Reason_name, Reason_value)
	proto.RegisterType((*NetworkConfig)(nil), "onos.config.network.NetworkConfig")
}

func init() { proto.RegisterFile("pkg/store/network/network.proto", fileDescriptor_f93f65a36c7c529a) }

var fileDescriptor_f93f65a36c7c529a = []byte{
	// 495 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0xe3, 0x76, 0x4b, 0x1b, 0xaf, 0x83, 0xca, 0x70, 0xb0, 0x0a, 0x4a, 0x2a, 0xc4, 0xa1,
	0x9a, 0x84, 0x23, 0x6d, 0x48, 0xdc, 0x26, 0xda, 0x26, 0x40, 0xa4, 0xaa, 0x54, 0x1e, 0x43, 0xe2,
	0x84, 0xd2, 0xc6, 0xf3, 0xc2, 0x68, 0x1c, 0x62, 0x07, 0xbe, 0xc6, 0x3e, 0xd6, 0x8e, 0x3b, 0x72,
	0x2a, 0x28, 0xfd, 0x16, 0x3d, 0xa1, 0x38, 0x09, 0x70, 0x40, 0x48, 0xbb, 0xe4, 0xbd, 0x3c, 0xff,
	0x7f, 0xcf, 0xcf, 0xef, 0x0f, 0x9d, 0xf4, 0x8a, 0xbb, 0x52, 0x89, 0x8c, 0xb9, 0x09, 0x53, 0xdf,
	0x44, 0x76, 0xd5, 0x44, 0x92, 0x66, 0x42, 0x09, 0xf4, 0x40, 0x24, 0x42, 0x92, 0x95, 0x48, 0x2e,
	0x62, 0x4e, 0xea, 0xa3, 0x81, 0xc3, 0x85, 0xe0, 0x9f, 0x99, 0xab, 0x25, 0xcb, 0xfc, 0xc2, 0x55,
	0xf1, 0x9a, 0x49, 0x15, 0xae, 0xd3, 0x8a, 0x1a, 0x3c, 0xe4, 0x82, 0x0b, 0x9d, 0xba, 0x65, 0x56,
	0x57, 0x5f, 0xf2, 0x58, 0x5d, 0xe6, 0x4b, 0xb2, 0x12, 0x6b, 0xb7, 0x6c, 0x9b, 0x66, 0xe2, 0x13,
	0x5b, 0x29, 0x9d, 0x3f, 0xab, 0xae, 0x70, 0xff, 0xcc, 0xb3, 0xba, 0x0c, 0x13, 0xde, 0x84, 0xaa,
	0xc3, 0x93, 0x5d, 0x1b, 0x1e, 0xce, 0xab, 0x21, 0xa6, 0x5a, 0x8f, 0x1e, 0xc3, 0x56, 0x1c, 0x61,
	0x30, 0x04, 0x23, 0x6b, 0xd2, 0x2b, 0x36, 0x4e, 0x2b, 0xf0, 0x76, 0xfa, 0x4b, 0x5b, 0x71, 0x84,
	0x38, 0x84, 0x19, 0xfb, 0x92, 0x33, 0xa9, 0x3e, 0xc6, 0x11, 0x6e, 0x0d, 0xc1, 0x68, 0x6f, 0xf2,
	0xa6, 0xd8, 0x38, 0x16, 0xad, 0xaa, 0x5a, 0xfc, 0xe2, 0x4e, 0x63, 0xd5, 0xfd, 0x48, 0xe0, 0x51,
	0xab, 0xce, 0x83, 0x08, 0x8d, 0x60, 0x37, 0x63, 0x5f, 0x63, 0x19, 0x8b, 0x04, 0xb7, 0xf5, 0x35,
	0xbd, 0xdd, 0xc6, 0xe9, 0xd2, 0xba, 0x46, 0x7f, 0x9f, 0xa2, 0x13, 0x68, 0x4a, 0x15, 0xaa, 0x5c,
	0xe2, 0xbd, 0x21, 0x18, 0xdd, 0x3b, 0x7e, 0x44, 0xfe, 0xb1, 0x61, 0x72, 0xa6, 0x25, 0xb4, 0x96,
	0x96, 0x50, 0xc6, 0x42, 0x29, 0x12, 0xbc, 0xff, 0x1f, 0x88, 0x6a, 0x09, 0xad, 0xa5, 0x08, 0xc3,
	0xce, 0x9a, 0x49, 0x19, 0x72, 0x86, 0xcd, 0x72, 0x3f, 0xb4, 0xf9, 0x45, 0xa7, 0xb0, 0xb3, 0xca,
	0x58, 0xa8, 0x58, 0x84, 0x3b, 0x43, 0x30, 0x3a, 0x38, 0x1e, 0x90, 0xca, 0x51, 0xd2, 0x38, 0x4a,
	0xde, 0x35, 0x8e, 0x4e, 0xba, 0x37, 0x1b, 0xc7, 0xb8, 0xfe, 0xe1, 0x00, 0xda, 0x40, 0x25, 0x9f,
	0xa7, 0x91, 0xe6, 0xbb, 0x77, 0xe1, 0x6b, 0x08, 0x3d, 0x87, 0x9d, 0xca, 0x56, 0x89, 0xad, 0x61,
	0x5b, 0xf3, 0x7f, 0xbf, 0xa7, 0xb6, 0x7c, 0xaa, 0x03, 0x6d, 0xa4, 0x47, 0xa7, 0xd0, 0xac, 0xd6,
	0x82, 0x0e, 0x60, 0x67, 0xe1, 0xcf, 0xbd, 0x60, 0xfe, 0xba, 0x6f, 0xa0, 0x1e, 0xec, 0x8e, 0x17,
	0x8b, 0xd9, 0x87, 0xf2, 0x0f, 0xa0, 0x43, 0x68, 0x9d, 0x9d, 0x4f, 0xa7, 0xbe, 0xef, 0xf9, 0x5e,
	0xbf, 0x85, 0x20, 0x34, 0x5f, 0x8d, 0x83, 0x99, 0xef, 0xf5, 0xdb, 0x47, 0x4f, 0xa1, 0x59, 0x6d,
	0x08, 0x59, 0x70, 0xdf, 0xa7, 0xf4, 0x2d, 0xed, 0x1b, 0xe8, 0x3e, 0x3c, 0x38, 0x9f, 0x8f, 0xdf,
	0x8f, 0x83, 0xd9, 0x78, 0x32, 0xf3, 0xfb, 0x60, 0x82, 0x6f, 0x0a, 0x1b, 0xdc, 0x16, 0x36, 0xf8,
	0x59, 0xd8, 0xe0, 0x7a, 0x6b, 0x1b, 0xb7, 0x5b, 0xdb, 0xf8, 0xbe, 0xb5, 0x8d, 0xa5, 0xa9, 0x1f,
	0x77, 0xf2, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x88, 0xb7, 0x74, 0x34, 0x03, 0x00, 0x00,
}

func (m *NetworkConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NetworkConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NetworkConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Changes) > 0 {
		for iNdEx := len(m.Changes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Changes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintNetwork(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.Updated, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.Updated):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintNetwork(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x42
	n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.Created, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.Created):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintNetwork(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x3a
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintNetwork(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0x32
	}
	if m.Reason != 0 {
		i = encodeVarintNetwork(dAtA, i, uint64(m.Reason))
		i--
		dAtA[i] = 0x28
	}
	if m.Status != 0 {
		i = encodeVarintNetwork(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x20
	}
	if m.Revision != 0 {
		i = encodeVarintNetwork(dAtA, i, uint64(m.Revision))
		i--
		dAtA[i] = 0x18
	}
	if m.RequestID != 0 {
		i = encodeVarintNetwork(dAtA, i, uint64(m.RequestID))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ID) > 0 {
		i -= len(m.ID)
		copy(dAtA[i:], m.ID)
		i = encodeVarintNetwork(dAtA, i, uint64(len(m.ID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintNetwork(dAtA []byte, offset int, v uint64) int {
	offset -= sovNetwork(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *NetworkConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovNetwork(uint64(l))
	}
	if m.RequestID != 0 {
		n += 1 + sovNetwork(uint64(m.RequestID))
	}
	if m.Revision != 0 {
		n += 1 + sovNetwork(uint64(m.Revision))
	}
	if m.Status != 0 {
		n += 1 + sovNetwork(uint64(m.Status))
	}
	if m.Reason != 0 {
		n += 1 + sovNetwork(uint64(m.Reason))
	}
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovNetwork(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.Created)
	n += 1 + l + sovNetwork(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.Updated)
	n += 1 + l + sovNetwork(uint64(l))
	if len(m.Changes) > 0 {
		for _, e := range m.Changes {
			l = e.Size()
			n += 1 + l + sovNetwork(uint64(l))
		}
	}
	return n
}

func sovNetwork(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozNetwork(x uint64) (n int) {
	return sovNetwork(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *NetworkConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNetwork
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NetworkConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NetworkConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNetwork
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNetwork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = ID(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestID", wireType)
			}
			m.RequestID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestID |= github_com_onosproject_onos_config_pkg_store_request.ID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Revision", wireType)
			}
			m.Revision = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Revision |= Revision(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			m.Reason = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Reason |= Reason(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNetwork
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNetwork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Created", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNetwork
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNetwork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.Created, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Updated", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNetwork
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNetwork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.Updated, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Changes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNetwork
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNetwork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Changes = append(m.Changes, &change.Change{})
			if err := m.Changes[len(m.Changes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNetwork(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNetwork
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthNetwork
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNetwork(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNetwork
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthNetwork
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthNetwork
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowNetwork
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipNetwork(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthNetwork
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthNetwork = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNetwork   = fmt.Errorf("proto: integer overflow")
)
