// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/northbound/admin/admin.proto

// Package admin defines the administrative and diagnostic gRPC interfaces.

package admin

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	change "github.com/onosproject/onos-config/pkg/types/change"
	network "github.com/onosproject/onos-config/pkg/types/network"
	gnmi "github.com/openconfig/gnmi/proto/gnmi"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// NetworkChangesRequest is a message for specifying GetNetworkChanges query parameters.
type NetworkChangesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkChangesRequest) Reset()         { *m = NetworkChangesRequest{} }
func (m *NetworkChangesRequest) String() string { return proto.CompactTextString(m) }
func (*NetworkChangesRequest) ProtoMessage()    {}
func (*NetworkChangesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{0}
}
func (m *NetworkChangesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkChangesRequest.Unmarshal(m, b)
}
func (m *NetworkChangesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkChangesRequest.Marshal(b, m, deterministic)
}
func (m *NetworkChangesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkChangesRequest.Merge(m, src)
}
func (m *NetworkChangesRequest) XXX_Size() int {
	return xxx_messageInfo_NetworkChangesRequest.Size(m)
}
func (m *NetworkChangesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkChangesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkChangesRequest proto.InternalMessageInfo

type ReadOnlySubPath struct {
	SubPath              string           `protobuf:"bytes,1,opt,name=sub_path,json=subPath,proto3" json:"sub_path,omitempty"`
	ValueType            change.ValueType `protobuf:"varint,2,opt,name=value_type,json=valueType,proto3,enum=onos.config.change.ValueType" json:"value_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReadOnlySubPath) Reset()         { *m = ReadOnlySubPath{} }
func (m *ReadOnlySubPath) String() string { return proto.CompactTextString(m) }
func (*ReadOnlySubPath) ProtoMessage()    {}
func (*ReadOnlySubPath) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{1}
}
func (m *ReadOnlySubPath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadOnlySubPath.Unmarshal(m, b)
}
func (m *ReadOnlySubPath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadOnlySubPath.Marshal(b, m, deterministic)
}
func (m *ReadOnlySubPath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadOnlySubPath.Merge(m, src)
}
func (m *ReadOnlySubPath) XXX_Size() int {
	return xxx_messageInfo_ReadOnlySubPath.Size(m)
}
func (m *ReadOnlySubPath) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadOnlySubPath.DiscardUnknown(m)
}

var xxx_messageInfo_ReadOnlySubPath proto.InternalMessageInfo

func (m *ReadOnlySubPath) GetSubPath() string {
	if m != nil {
		return m.SubPath
	}
	return ""
}

func (m *ReadOnlySubPath) GetValueType() change.ValueType {
	if m != nil {
		return m.ValueType
	}
	return change.ValueType_EMPTY
}

type ReadOnlyPath struct {
	Path                 string             `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	SubPath              []*ReadOnlySubPath `protobuf:"bytes,2,rep,name=sub_path,json=subPath,proto3" json:"sub_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ReadOnlyPath) Reset()         { *m = ReadOnlyPath{} }
func (m *ReadOnlyPath) String() string { return proto.CompactTextString(m) }
func (*ReadOnlyPath) ProtoMessage()    {}
func (*ReadOnlyPath) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{2}
}
func (m *ReadOnlyPath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadOnlyPath.Unmarshal(m, b)
}
func (m *ReadOnlyPath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadOnlyPath.Marshal(b, m, deterministic)
}
func (m *ReadOnlyPath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadOnlyPath.Merge(m, src)
}
func (m *ReadOnlyPath) XXX_Size() int {
	return xxx_messageInfo_ReadOnlyPath.Size(m)
}
func (m *ReadOnlyPath) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadOnlyPath.DiscardUnknown(m)
}

var xxx_messageInfo_ReadOnlyPath proto.InternalMessageInfo

func (m *ReadOnlyPath) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ReadOnlyPath) GetSubPath() []*ReadOnlySubPath {
	if m != nil {
		return m.SubPath
	}
	return nil
}

type ReadWritePath struct {
	Path                 string           `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ValueType            change.ValueType `protobuf:"varint,2,opt,name=value_type,json=valueType,proto3,enum=onos.config.change.ValueType" json:"value_type,omitempty"`
	Units                string           `protobuf:"bytes,3,opt,name=units,proto3" json:"units,omitempty"`
	Description          string           `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Mandatory            bool             `protobuf:"varint,5,opt,name=mandatory,proto3" json:"mandatory,omitempty"`
	Default              string           `protobuf:"bytes,6,opt,name=default,proto3" json:"default,omitempty"`
	Range                []string         `protobuf:"bytes,7,rep,name=range,proto3" json:"range,omitempty"`
	Length               []string         `protobuf:"bytes,8,rep,name=length,proto3" json:"length,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReadWritePath) Reset()         { *m = ReadWritePath{} }
func (m *ReadWritePath) String() string { return proto.CompactTextString(m) }
func (*ReadWritePath) ProtoMessage()    {}
func (*ReadWritePath) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{3}
}
func (m *ReadWritePath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadWritePath.Unmarshal(m, b)
}
func (m *ReadWritePath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadWritePath.Marshal(b, m, deterministic)
}
func (m *ReadWritePath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadWritePath.Merge(m, src)
}
func (m *ReadWritePath) XXX_Size() int {
	return xxx_messageInfo_ReadWritePath.Size(m)
}
func (m *ReadWritePath) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadWritePath.DiscardUnknown(m)
}

var xxx_messageInfo_ReadWritePath proto.InternalMessageInfo

func (m *ReadWritePath) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ReadWritePath) GetValueType() change.ValueType {
	if m != nil {
		return m.ValueType
	}
	return change.ValueType_EMPTY
}

func (m *ReadWritePath) GetUnits() string {
	if m != nil {
		return m.Units
	}
	return ""
}

func (m *ReadWritePath) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ReadWritePath) GetMandatory() bool {
	if m != nil {
		return m.Mandatory
	}
	return false
}

func (m *ReadWritePath) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

func (m *ReadWritePath) GetRange() []string {
	if m != nil {
		return m.Range
	}
	return nil
}

func (m *ReadWritePath) GetLength() []string {
	if m != nil {
		return m.Length
	}
	return nil
}

type ModelInfo struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ModelData            []*gnmi.ModelData `protobuf:"bytes,3,rep,name=model_data,json=modelData,proto3" json:"model_data,omitempty"`
	Module               string            `protobuf:"bytes,4,opt,name=module,proto3" json:"module,omitempty"`
	ReadOnlyPath         []*ReadOnlyPath   `protobuf:"bytes,7,rep,name=read_only_path,json=readOnlyPath,proto3" json:"read_only_path,omitempty"`
	ReadWritePath        []*ReadWritePath  `protobuf:"bytes,8,rep,name=read_write_path,json=readWritePath,proto3" json:"read_write_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ModelInfo) Reset()         { *m = ModelInfo{} }
func (m *ModelInfo) String() string { return proto.CompactTextString(m) }
func (*ModelInfo) ProtoMessage()    {}
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{4}
}
func (m *ModelInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelInfo.Unmarshal(m, b)
}
func (m *ModelInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelInfo.Marshal(b, m, deterministic)
}
func (m *ModelInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelInfo.Merge(m, src)
}
func (m *ModelInfo) XXX_Size() int {
	return xxx_messageInfo_ModelInfo.Size(m)
}
func (m *ModelInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ModelInfo proto.InternalMessageInfo

func (m *ModelInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModelInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ModelInfo) GetModelData() []*gnmi.ModelData {
	if m != nil {
		return m.ModelData
	}
	return nil
}

func (m *ModelInfo) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *ModelInfo) GetReadOnlyPath() []*ReadOnlyPath {
	if m != nil {
		return m.ReadOnlyPath
	}
	return nil
}

func (m *ModelInfo) GetReadWritePath() []*ReadWritePath {
	if m != nil {
		return m.ReadWritePath
	}
	return nil
}

// Chunk is for streaming a model plugin file to the server
// There is a built in limit in gRPC of 4MB - plugin is usually around 20MB
// so break in to chunks of approx 1MB
type Chunk struct {
	SoFile               string   `protobuf:"bytes,1,opt,name=so_file,json=soFile,proto3" json:"so_file,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chunk) Reset()         { *m = Chunk{} }
func (m *Chunk) String() string { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()    {}
func (*Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{5}
}
func (m *Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk.Unmarshal(m, b)
}
func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk.Marshal(b, m, deterministic)
}
func (m *Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk.Merge(m, src)
}
func (m *Chunk) XXX_Size() int {
	return xxx_messageInfo_Chunk.Size(m)
}
func (m *Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk proto.InternalMessageInfo

func (m *Chunk) GetSoFile() string {
	if m != nil {
		return m.SoFile
	}
	return ""
}

func (m *Chunk) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

// RegisterRequest carries data for registering a YANG model.
type RegisterRequest struct {
	// Full path and filename of a shared object library as a model plugin
	SoFile               string   `protobuf:"bytes,1,opt,name=so_file,json=soFile,proto3" json:"so_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{6}
}
func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetSoFile() string {
	if m != nil {
		return m.SoFile
	}
	return ""
}

type SchemaEntry struct {
	SchemaPath           string   `protobuf:"bytes,1,opt,name=schema_path,json=schemaPath,proto3" json:"schema_path,omitempty"`
	SchemaJson           string   `protobuf:"bytes,2,opt,name=schema_json,json=schemaJson,proto3" json:"schema_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchemaEntry) Reset()         { *m = SchemaEntry{} }
func (m *SchemaEntry) String() string { return proto.CompactTextString(m) }
func (*SchemaEntry) ProtoMessage()    {}
func (*SchemaEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{7}
}
func (m *SchemaEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemaEntry.Unmarshal(m, b)
}
func (m *SchemaEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemaEntry.Marshal(b, m, deterministic)
}
func (m *SchemaEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemaEntry.Merge(m, src)
}
func (m *SchemaEntry) XXX_Size() int {
	return xxx_messageInfo_SchemaEntry.Size(m)
}
func (m *SchemaEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemaEntry.DiscardUnknown(m)
}

var xxx_messageInfo_SchemaEntry proto.InternalMessageInfo

func (m *SchemaEntry) GetSchemaPath() string {
	if m != nil {
		return m.SchemaPath
	}
	return ""
}

func (m *SchemaEntry) GetSchemaJson() string {
	if m != nil {
		return m.SchemaJson
	}
	return ""
}

// RegisterResponse carries status of YANG model registration.
type RegisterResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{8}
}
func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// ListModelsRequest carries data for querying registered models.
type ListModelsRequest struct {
	Verbose              bool     `protobuf:"varint,1,opt,name=verbose,proto3" json:"verbose,omitempty"`
	ModelName            string   `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	ModelVersion         string   `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListModelsRequest) Reset()         { *m = ListModelsRequest{} }
func (m *ListModelsRequest) String() string { return proto.CompactTextString(m) }
func (*ListModelsRequest) ProtoMessage()    {}
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{9}
}
func (m *ListModelsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListModelsRequest.Unmarshal(m, b)
}
func (m *ListModelsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListModelsRequest.Marshal(b, m, deterministic)
}
func (m *ListModelsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListModelsRequest.Merge(m, src)
}
func (m *ListModelsRequest) XXX_Size() int {
	return xxx_messageInfo_ListModelsRequest.Size(m)
}
func (m *ListModelsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListModelsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListModelsRequest proto.InternalMessageInfo

func (m *ListModelsRequest) GetVerbose() bool {
	if m != nil {
		return m.Verbose
	}
	return false
}

func (m *ListModelsRequest) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

func (m *ListModelsRequest) GetModelVersion() string {
	if m != nil {
		return m.ModelVersion
	}
	return ""
}

// RollbackRequest carries the name of a network config to rollback. If there
// are subsequent changes to any of the devices in that config, the rollback will
// be rejected. If no name is given the last network change will be rolled back.
type RollbackRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Comment              string   `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollbackRequest) Reset()         { *m = RollbackRequest{} }
func (m *RollbackRequest) String() string { return proto.CompactTextString(m) }
func (*RollbackRequest) ProtoMessage()    {}
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{10}
}
func (m *RollbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollbackRequest.Unmarshal(m, b)
}
func (m *RollbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollbackRequest.Marshal(b, m, deterministic)
}
func (m *RollbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollbackRequest.Merge(m, src)
}
func (m *RollbackRequest) XXX_Size() int {
	return xxx_messageInfo_RollbackRequest.Size(m)
}
func (m *RollbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RollbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RollbackRequest proto.InternalMessageInfo

func (m *RollbackRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RollbackRequest) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type RollbackResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollbackResponse) Reset()         { *m = RollbackResponse{} }
func (m *RollbackResponse) String() string { return proto.CompactTextString(m) }
func (*RollbackResponse) ProtoMessage()    {}
func (*RollbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9081d84c442224d8, []int{11}
}
func (m *RollbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollbackResponse.Unmarshal(m, b)
}
func (m *RollbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollbackResponse.Marshal(b, m, deterministic)
}
func (m *RollbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollbackResponse.Merge(m, src)
}
func (m *RollbackResponse) XXX_Size() int {
	return xxx_messageInfo_RollbackResponse.Size(m)
}
func (m *RollbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RollbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RollbackResponse proto.InternalMessageInfo

func (m *RollbackResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*NetworkChangesRequest)(nil), "onos.config.admin.NetworkChangesRequest")
	proto.RegisterType((*ReadOnlySubPath)(nil), "onos.config.admin.ReadOnlySubPath")
	proto.RegisterType((*ReadOnlyPath)(nil), "onos.config.admin.ReadOnlyPath")
	proto.RegisterType((*ReadWritePath)(nil), "onos.config.admin.ReadWritePath")
	proto.RegisterType((*ModelInfo)(nil), "onos.config.admin.ModelInfo")
	proto.RegisterType((*Chunk)(nil), "onos.config.admin.Chunk")
	proto.RegisterType((*RegisterRequest)(nil), "onos.config.admin.RegisterRequest")
	proto.RegisterType((*SchemaEntry)(nil), "onos.config.admin.SchemaEntry")
	proto.RegisterType((*RegisterResponse)(nil), "onos.config.admin.RegisterResponse")
	proto.RegisterType((*ListModelsRequest)(nil), "onos.config.admin.ListModelsRequest")
	proto.RegisterType((*RollbackRequest)(nil), "onos.config.admin.RollbackRequest")
	proto.RegisterType((*RollbackResponse)(nil), "onos.config.admin.RollbackResponse")
}

func init() { proto.RegisterFile("pkg/northbound/admin/admin.proto", fileDescriptor_9081d84c442224d8) }

var fileDescriptor_9081d84c442224d8 = []byte{
	// 819 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x6d, 0x8f, 0xdb, 0x44,
	0x10, 0x96, 0x2f, 0xbd, 0x4b, 0x32, 0xc9, 0x35, 0xbd, 0xe5, 0x4a, 0x4d, 0xd4, 0xaa, 0x96, 0xcb,
	0x87, 0x08, 0x81, 0x73, 0x3a, 0xbe, 0x21, 0x10, 0x85, 0x50, 0xde, 0x04, 0x2d, 0xf2, 0xc1, 0xc1,
	0x07, 0xa4, 0xb0, 0xb1, 0x37, 0xb6, 0x2f, 0xf6, 0xae, 0xeb, 0x5d, 0xa7, 0xca, 0xdf, 0xe0, 0x6f,
	0xf2, 0x23, 0x40, 0xfb, 0x96, 0x38, 0xad, 0x53, 0x71, 0xea, 0x97, 0x64, 0x67, 0x77, 0xe6, 0x79,
	0x66, 0xe6, 0x99, 0xf5, 0x82, 0x57, 0xae, 0x92, 0x29, 0x65, 0x95, 0x48, 0x17, 0xac, 0xa6, 0xf1,
	0x14, 0xc7, 0x45, 0x46, 0xf5, 0x6f, 0x50, 0x56, 0x4c, 0x30, 0x74, 0xc6, 0x28, 0xe3, 0x41, 0xc4,
	0xe8, 0x32, 0x4b, 0x02, 0x75, 0x30, 0x3e, 0x4f, 0x58, 0xc2, 0xd4, 0xe9, 0x54, 0xae, 0xb4, 0xe3,
	0xf8, 0x22, 0xc9, 0x44, 0x5a, 0x2f, 0x82, 0x88, 0x15, 0x53, 0x56, 0x12, 0xaa, 0x43, 0xa6, 0x09,
	0x2d, 0xb2, 0xa9, 0x71, 0x96, 0x4b, 0xf9, 0x63, 0x22, 0x9e, 0x36, 0x23, 0x28, 0xe3, 0x65, 0xc5,
	0x6e, 0x48, 0x24, 0xd4, 0xfa, 0x13, 0x13, 0x2e, 0xf3, 0x13, 0x9b, 0x92, 0xf0, 0x69, 0x94, 0x62,
	0x9a, 0x10, 0xf3, 0x67, 0x10, 0xbe, 0xbe, 0x15, 0x02, 0x25, 0xe2, 0x15, 0xab, 0x56, 0xf6, 0x5f,
	0x63, 0xf8, 0x0f, 0xe0, 0xfe, 0x73, 0xbd, 0x31, 0x53, 0xd0, 0x3c, 0x24, 0x2f, 0x6b, 0xc2, 0x85,
	0x7f, 0x03, 0xa3, 0x90, 0xe0, 0xf8, 0x05, 0xcd, 0x37, 0x57, 0xf5, 0xe2, 0x17, 0x2c, 0x52, 0xf4,
	0x01, 0xf4, 0x78, 0xbd, 0x98, 0x97, 0x58, 0xa4, 0xae, 0xe3, 0x39, 0x93, 0x7e, 0xd8, 0xe5, 0xe6,
	0xe8, 0x73, 0x80, 0x35, 0xce, 0x6b, 0x32, 0x97, 0x5c, 0xee, 0x91, 0xe7, 0x4c, 0xee, 0x5e, 0x3e,
	0x0a, 0x9a, 0xcd, 0x33, 0x99, 0x5f, 0x4b, 0xaf, 0x5f, 0x37, 0x25, 0x09, 0xfb, 0x6b, 0xbb, 0xf4,
	0x31, 0x0c, 0x2d, 0x97, 0x42, 0x43, 0x70, 0xa7, 0x41, 0xa2, 0xd6, 0xe8, 0x8b, 0x06, 0xf9, 0x91,
	0xd7, 0x99, 0x0c, 0x2e, 0xfd, 0xe0, 0x0d, 0x71, 0x82, 0xd7, 0x52, 0xde, 0x26, 0xe8, 0xff, 0xeb,
	0xc0, 0xa9, 0x3c, 0xfc, 0xbd, 0xca, 0x04, 0x39, 0x48, 0xf2, 0x4e, 0x65, 0xa0, 0x73, 0x38, 0xae,
	0x69, 0x26, 0xb8, 0xdb, 0x51, 0x90, 0xda, 0x40, 0x1e, 0x0c, 0x62, 0xc2, 0xa3, 0x2a, 0x2b, 0x45,
	0xc6, 0xa8, 0x7b, 0x47, 0x9d, 0x35, 0xb7, 0xd0, 0x43, 0xe8, 0x17, 0x98, 0xc6, 0x58, 0xb0, 0x6a,
	0xe3, 0x1e, 0x7b, 0xce, 0xa4, 0x17, 0xee, 0x36, 0x90, 0x0b, 0xdd, 0x98, 0x2c, 0x71, 0x9d, 0x0b,
	0xf7, 0x44, 0x37, 0xdd, 0x98, 0x92, 0xaf, 0x92, 0xd9, 0xb8, 0x5d, 0xaf, 0x23, 0xf9, 0x94, 0x81,
	0xde, 0x87, 0x93, 0x9c, 0xd0, 0x44, 0xa4, 0x6e, 0x4f, 0x6d, 0x1b, 0xcb, 0xff, 0xfb, 0x08, 0xfa,
	0x3f, 0xb3, 0x98, 0xe4, 0x3f, 0xd0, 0x25, 0x93, 0xd5, 0x53, 0x5c, 0x10, 0x5b, 0xbd, 0x5c, 0x4b,
	0xa6, 0x35, 0xa9, 0xb8, 0xcc, 0xf2, 0x48, 0x33, 0x19, 0x13, 0x05, 0x00, 0x85, 0x0c, 0x9d, 0xc7,
	0x58, 0x60, 0xb7, 0xa3, 0xda, 0x3f, 0x0a, 0xd4, 0x30, 0x2b, 0xc8, 0x6f, 0xb0, 0xc0, 0x61, 0xbf,
	0xb0, 0x4b, 0x99, 0x43, 0xc1, 0xe2, 0x3a, 0x27, 0xa6, 0x5c, 0x63, 0xa1, 0x67, 0x70, 0xb7, 0x22,
	0x38, 0x9e, 0x33, 0x9a, 0x6f, 0xb4, 0x94, 0x5d, 0x85, 0xf5, 0xf8, 0x2d, 0x52, 0x2a, 0x1d, 0x87,
	0x55, 0x73, 0x3e, 0xbe, 0x87, 0x91, 0x82, 0x79, 0x25, 0xc5, 0xd4, 0x38, 0x3d, 0x85, 0xe3, 0x1d,
	0xc0, 0xd9, 0xaa, 0x1e, 0x9e, 0x56, 0x4d, 0xd3, 0xff, 0x0c, 0x8e, 0x67, 0x69, 0x4d, 0x57, 0xe8,
	0x01, 0x74, 0x39, 0x9b, 0x2f, 0xb3, 0xdc, 0xb6, 0xe4, 0x84, 0xb3, 0x6f, 0xb3, 0x5c, 0x35, 0x65,
	0xc6, 0xa8, 0x20, 0x54, 0xa8, 0xa6, 0x0c, 0x43, 0x6b, 0xfa, 0x1f, 0xc9, 0x1b, 0x92, 0x64, 0x5c,
	0x90, 0xca, 0x5c, 0x9a, 0x83, 0x28, 0xfe, 0x0b, 0x18, 0x5c, 0x45, 0x29, 0x29, 0xf0, 0x33, 0x2a,
	0xaa, 0x0d, 0x7a, 0x0c, 0x03, 0xae, 0xcc, 0xe6, 0x65, 0x02, 0xbd, 0xa5, 0x2a, 0xdc, 0x39, 0xdc,
	0xf0, 0xad, 0x1c, 0xc6, 0xe1, 0x47, 0xce, 0xa8, 0xff, 0x14, 0xee, 0xed, 0xc8, 0x79, 0xc9, 0x28,
	0x27, 0xb7, 0xd3, 0xd4, 0x7f, 0x09, 0x67, 0x3f, 0x65, 0x5c, 0x28, 0xfd, 0xec, 0xad, 0x37, 0xee,
	0x0b, 0xc6, 0x35, 0x4a, 0x2f, 0xb4, 0x26, 0x7a, 0x64, 0x47, 0x40, 0x51, 0x68, 0x2c, 0xad, 0xf8,
	0x73, 0xc9, 0xf3, 0x04, 0x4e, 0xf5, 0xb1, 0x65, 0xd3, 0x77, 0x60, 0xa8, 0x36, 0xaf, 0x0d, 0xe5,
	0x97, 0x30, 0x0a, 0x59, 0x9e, 0x2f, 0x70, 0xb4, 0xb2, 0x84, 0x07, 0x72, 0x8e, 0x58, 0x51, 0xd8,
	0x96, 0xf7, 0x43, 0x6b, 0xfa, 0x1f, 0xc3, 0xbd, 0x1d, 0x80, 0xa9, 0xda, 0x85, 0x6e, 0x41, 0x38,
	0xc7, 0x89, 0x05, 0xb1, 0xe6, 0xe5, 0x3f, 0x1d, 0x40, 0x33, 0x35, 0x0a, 0x5f, 0xc9, 0x49, 0xb8,
	0x22, 0xd5, 0x3a, 0x8b, 0x08, 0xfa, 0x43, 0x7e, 0x09, 0x74, 0xeb, 0x54, 0xf1, 0xa8, 0xfd, 0x43,
	0xb2, 0xa7, 0xec, 0xf8, 0xc9, 0x5b, 0x7d, 0x4c, 0x2a, 0xd7, 0xf0, 0xde, 0x6f, 0x65, 0xce, 0x70,
	0xbc, 0x8f, 0xef, 0xb6, 0xc4, 0xaa, 0xa9, 0xfb, 0x5f, 0xa8, 0x13, 0x07, 0xfd, 0x09, 0xe7, 0x52,
	0x2a, 0x7b, 0x42, 0x62, 0x2d, 0x1a, 0xfa, 0xb0, 0x25, 0xfc, 0x0d, 0x4d, 0xc7, 0x0f, 0x5b, 0xbc,
	0xb6, 0x1f, 0x82, 0x0b, 0x07, 0x45, 0x70, 0xf6, 0x1d, 0x11, 0xfb, 0xaf, 0x00, 0x9a, 0xb4, 0x04,
	0xb5, 0x3e, 0x14, 0xe3, 0xfd, 0xee, 0xd9, 0xd7, 0xc5, 0xfa, 0xaa, 0xdd, 0x0b, 0x07, 0xfd, 0x05,
	0xf7, 0xad, 0x72, 0x7b, 0x30, 0xed, 0xcd, 0xdf, 0x1f, 0x92, 0xf6, 0x36, 0xbd, 0x36, 0x07, 0x8b,
	0x13, 0xf5, 0xa0, 0x7d, 0xfa, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x1e, 0x4b, 0x2b, 0xd5,
	0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConfigAdminServiceClient is the client API for ConfigAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConfigAdminServiceClient interface {
	// RegisterModel adds the specified YANG model to the list of supported models.
	// There is no unregister because once loaded plugins cannot be unloaded
	RegisterModel(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// UploadRegisterModel uploads and adds the model plugin to the list of supported models.
	UploadRegisterModel(ctx context.Context, opts ...grpc.CallOption) (ConfigAdminService_UploadRegisterModelClient, error)
	// ListRegisteredModels returns a stream of registered models.
	ListRegisteredModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (ConfigAdminService_ListRegisteredModelsClient, error)
	// GetNetworkChanges returns a stream of network changes submitted via gNMI.
	GetNetworkChanges(ctx context.Context, in *NetworkChangesRequest, opts ...grpc.CallOption) (ConfigAdminService_GetNetworkChangesClient, error)
	// RollbackNetworkChange rolls back the specified network change (or the latest one).
	RollbackNetworkChange(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error)
}

type configAdminServiceClient struct {
	cc *grpc.ClientConn
}

func NewConfigAdminServiceClient(cc *grpc.ClientConn) ConfigAdminServiceClient {
	return &configAdminServiceClient{cc}
}

func (c *configAdminServiceClient) RegisterModel(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/onos.config.admin.ConfigAdminService/RegisterModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configAdminServiceClient) UploadRegisterModel(ctx context.Context, opts ...grpc.CallOption) (ConfigAdminService_UploadRegisterModelClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ConfigAdminService_serviceDesc.Streams[0], "/onos.config.admin.ConfigAdminService/UploadRegisterModel", opts...)
	if err != nil {
		return nil, err
	}
	x := &configAdminServiceUploadRegisterModelClient{stream}
	return x, nil
}

type ConfigAdminService_UploadRegisterModelClient interface {
	Send(*Chunk) error
	CloseAndRecv() (*RegisterResponse, error)
	grpc.ClientStream
}

type configAdminServiceUploadRegisterModelClient struct {
	grpc.ClientStream
}

func (x *configAdminServiceUploadRegisterModelClient) Send(m *Chunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *configAdminServiceUploadRegisterModelClient) CloseAndRecv() (*RegisterResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(RegisterResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *configAdminServiceClient) ListRegisteredModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (ConfigAdminService_ListRegisteredModelsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ConfigAdminService_serviceDesc.Streams[1], "/onos.config.admin.ConfigAdminService/ListRegisteredModels", opts...)
	if err != nil {
		return nil, err
	}
	x := &configAdminServiceListRegisteredModelsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ConfigAdminService_ListRegisteredModelsClient interface {
	Recv() (*ModelInfo, error)
	grpc.ClientStream
}

type configAdminServiceListRegisteredModelsClient struct {
	grpc.ClientStream
}

func (x *configAdminServiceListRegisteredModelsClient) Recv() (*ModelInfo, error) {
	m := new(ModelInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *configAdminServiceClient) GetNetworkChanges(ctx context.Context, in *NetworkChangesRequest, opts ...grpc.CallOption) (ConfigAdminService_GetNetworkChangesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ConfigAdminService_serviceDesc.Streams[2], "/onos.config.admin.ConfigAdminService/GetNetworkChanges", opts...)
	if err != nil {
		return nil, err
	}
	x := &configAdminServiceGetNetworkChangesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ConfigAdminService_GetNetworkChangesClient interface {
	Recv() (*network.NetworkConfig, error)
	grpc.ClientStream
}

type configAdminServiceGetNetworkChangesClient struct {
	grpc.ClientStream
}

func (x *configAdminServiceGetNetworkChangesClient) Recv() (*network.NetworkConfig, error) {
	m := new(network.NetworkConfig)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *configAdminServiceClient) RollbackNetworkChange(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error) {
	out := new(RollbackResponse)
	err := c.cc.Invoke(ctx, "/onos.config.admin.ConfigAdminService/RollbackNetworkChange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigAdminServiceServer is the server API for ConfigAdminService service.
type ConfigAdminServiceServer interface {
	// RegisterModel adds the specified YANG model to the list of supported models.
	// There is no unregister because once loaded plugins cannot be unloaded
	RegisterModel(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// UploadRegisterModel uploads and adds the model plugin to the list of supported models.
	UploadRegisterModel(ConfigAdminService_UploadRegisterModelServer) error
	// ListRegisteredModels returns a stream of registered models.
	ListRegisteredModels(*ListModelsRequest, ConfigAdminService_ListRegisteredModelsServer) error
	// GetNetworkChanges returns a stream of network changes submitted via gNMI.
	GetNetworkChanges(*NetworkChangesRequest, ConfigAdminService_GetNetworkChangesServer) error
	// RollbackNetworkChange rolls back the specified network change (or the latest one).
	RollbackNetworkChange(context.Context, *RollbackRequest) (*RollbackResponse, error)
}

// UnimplementedConfigAdminServiceServer can be embedded to have forward compatible implementations.
type UnimplementedConfigAdminServiceServer struct {
}

func (*UnimplementedConfigAdminServiceServer) RegisterModel(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterModel not implemented")
}
func (*UnimplementedConfigAdminServiceServer) UploadRegisterModel(srv ConfigAdminService_UploadRegisterModelServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadRegisterModel not implemented")
}
func (*UnimplementedConfigAdminServiceServer) ListRegisteredModels(req *ListModelsRequest, srv ConfigAdminService_ListRegisteredModelsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListRegisteredModels not implemented")
}
func (*UnimplementedConfigAdminServiceServer) GetNetworkChanges(req *NetworkChangesRequest, srv ConfigAdminService_GetNetworkChangesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetNetworkChanges not implemented")
}
func (*UnimplementedConfigAdminServiceServer) RollbackNetworkChange(ctx context.Context, req *RollbackRequest) (*RollbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollbackNetworkChange not implemented")
}

func RegisterConfigAdminServiceServer(s *grpc.Server, srv ConfigAdminServiceServer) {
	s.RegisterService(&_ConfigAdminService_serviceDesc, srv)
}

func _ConfigAdminService_RegisterModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigAdminServiceServer).RegisterModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onos.config.admin.ConfigAdminService/RegisterModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigAdminServiceServer).RegisterModel(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigAdminService_UploadRegisterModel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConfigAdminServiceServer).UploadRegisterModel(&configAdminServiceUploadRegisterModelServer{stream})
}

type ConfigAdminService_UploadRegisterModelServer interface {
	SendAndClose(*RegisterResponse) error
	Recv() (*Chunk, error)
	grpc.ServerStream
}

type configAdminServiceUploadRegisterModelServer struct {
	grpc.ServerStream
}

func (x *configAdminServiceUploadRegisterModelServer) SendAndClose(m *RegisterResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *configAdminServiceUploadRegisterModelServer) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ConfigAdminService_ListRegisteredModels_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListModelsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfigAdminServiceServer).ListRegisteredModels(m, &configAdminServiceListRegisteredModelsServer{stream})
}

type ConfigAdminService_ListRegisteredModelsServer interface {
	Send(*ModelInfo) error
	grpc.ServerStream
}

type configAdminServiceListRegisteredModelsServer struct {
	grpc.ServerStream
}

func (x *configAdminServiceListRegisteredModelsServer) Send(m *ModelInfo) error {
	return x.ServerStream.SendMsg(m)
}

func _ConfigAdminService_GetNetworkChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NetworkChangesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfigAdminServiceServer).GetNetworkChanges(m, &configAdminServiceGetNetworkChangesServer{stream})
}

type ConfigAdminService_GetNetworkChangesServer interface {
	Send(*network.NetworkConfig) error
	grpc.ServerStream
}

type configAdminServiceGetNetworkChangesServer struct {
	grpc.ServerStream
}

func (x *configAdminServiceGetNetworkChangesServer) Send(m *network.NetworkConfig) error {
	return x.ServerStream.SendMsg(m)
}

func _ConfigAdminService_RollbackNetworkChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigAdminServiceServer).RollbackNetworkChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onos.config.admin.ConfigAdminService/RollbackNetworkChange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigAdminServiceServer).RollbackNetworkChange(ctx, req.(*RollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConfigAdminService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "onos.config.admin.ConfigAdminService",
	HandlerType: (*ConfigAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterModel",
			Handler:    _ConfigAdminService_RegisterModel_Handler,
		},
		{
			MethodName: "RollbackNetworkChange",
			Handler:    _ConfigAdminService_RollbackNetworkChange_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadRegisterModel",
			Handler:       _ConfigAdminService_UploadRegisterModel_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ListRegisteredModels",
			Handler:       _ConfigAdminService_ListRegisteredModels_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetNetworkChanges",
			Handler:       _ConfigAdminService_GetNetworkChanges_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/northbound/admin/admin.proto",
}
