// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/northbound/diags/diags.proto

package diags

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	change "github.com/onosproject/onos-config/pkg/types/change"
	github_com_onosproject_onos_topo_pkg_northbound_device "github.com/onosproject/onos-topo/pkg/northbound/device"
	github_com_onosproject_onos_topo_pkg_types_change "github.com/onosproject/onos-topo/pkg/types/change"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Streaming event type
type Type int32

const (
	// NONE indicates this response does not represent a state change
	Type_NONE Type = 0
	// ADDED is an event which occurs when an item is added
	Type_ADDED Type = 1
	// UPDATED is an event which occurs when an item is updated
	Type_UPDATED Type = 2
	// REMOVED is an event which occurs when an item is removed
	Type_REMOVED Type = 3
)

var Type_name = map[int32]string{
	0: "NONE",
	1: "ADDED",
	2: "UPDATED",
	3: "REMOVED",
}

var Type_value = map[string]int32{
	"NONE":    0,
	"ADDED":   1,
	"UPDATED": 2,
	"REMOVED": 3,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_624d839d9ad9df06, []int{0}
}

// ChangesRequest is a message for specifying GetChanges query parameters.
type ChangesRequest struct {
	ChangeIDs            []github_com_onosproject_onos_topo_pkg_types_change.ID `protobuf:"bytes,1,rep,name=change_ids,json=changeIds,proto3,casttype=github.com/onosproject/onos-topo/pkg/types/change.ID" json:"change_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                               `json:"-"`
	XXX_unrecognized     []byte                                                 `json:"-"`
	XXX_sizecache        int32                                                  `json:"-"`
}

func (m *ChangesRequest) Reset()         { *m = ChangesRequest{} }
func (m *ChangesRequest) String() string { return proto.CompactTextString(m) }
func (*ChangesRequest) ProtoMessage()    {}
func (*ChangesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_624d839d9ad9df06, []int{0}
}
func (m *ChangesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangesRequest.Unmarshal(m, b)
}
func (m *ChangesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangesRequest.Marshal(b, m, deterministic)
}
func (m *ChangesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangesRequest.Merge(m, src)
}
func (m *ChangesRequest) XXX_Size() int {
	return xxx_messageInfo_ChangesRequest.Size(m)
}
func (m *ChangesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangesRequest proto.InternalMessageInfo

func (m *ChangesRequest) GetChangeIDs() []github_com_onosproject_onos_topo_pkg_types_change.ID {
	if m != nil {
		return m.ChangeIDs
	}
	return nil
}

// ConfigRequest is a message for specifying GetConfigurations query parameters.
type ConfigRequest struct {
	DeviceIDs            []github_com_onosproject_onos_topo_pkg_northbound_device.ID `protobuf:"bytes,1,rep,name=device_ids,json=deviceIds,proto3,casttype=github.com/onosproject/onos-topo/pkg/northbound/device.ID" json:"device_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                    `json:"-"`
	XXX_unrecognized     []byte                                                      `json:"-"`
	XXX_sizecache        int32                                                       `json:"-"`
}

func (m *ConfigRequest) Reset()         { *m = ConfigRequest{} }
func (m *ConfigRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigRequest) ProtoMessage()    {}
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_624d839d9ad9df06, []int{1}
}
func (m *ConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigRequest.Unmarshal(m, b)
}
func (m *ConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigRequest.Marshal(b, m, deterministic)
}
func (m *ConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigRequest.Merge(m, src)
}
func (m *ConfigRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigRequest.Size(m)
}
func (m *ConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigRequest proto.InternalMessageInfo

func (m *ConfigRequest) GetDeviceIDs() []github_com_onosproject_onos_topo_pkg_northbound_device.ID {
	if m != nil {
		return m.DeviceIDs
	}
	return nil
}

// OpStateRequest is a message for specifying GetOpState query parameters.
type OpStateRequest struct {
	// The request is always in the context of a Device ID. If the device does
	// not exist or is disconnected an error will be returned.
	DeviceId string `protobuf:"bytes,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	// subscribe indicates whether to subscribe to events (e.g. ADD, UPDATE, and REMOVE) that occur
	// after all paths for the device have been streamed to the client
	Subscribe            bool     `protobuf:"varint,2,opt,name=subscribe,proto3" json:"subscribe,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpStateRequest) Reset()         { *m = OpStateRequest{} }
func (m *OpStateRequest) String() string { return proto.CompactTextString(m) }
func (*OpStateRequest) ProtoMessage()    {}
func (*OpStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_624d839d9ad9df06, []int{2}
}
func (m *OpStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpStateRequest.Unmarshal(m, b)
}
func (m *OpStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpStateRequest.Marshal(b, m, deterministic)
}
func (m *OpStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpStateRequest.Merge(m, src)
}
func (m *OpStateRequest) XXX_Size() int {
	return xxx_messageInfo_OpStateRequest.Size(m)
}
func (m *OpStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpStateRequest proto.InternalMessageInfo

func (m *OpStateRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *OpStateRequest) GetSubscribe() bool {
	if m != nil {
		return m.Subscribe
	}
	return false
}

type OpStateResponse struct {
	// type is the type of the event
	Type Type `protobuf:"varint,1,opt,name=type,proto3,enum=onos.config.diags.Type" json:"type,omitempty"`
	// device is the device on which the event occurred
	Pathvalue            *change.Value `protobuf:"bytes,2,opt,name=pathvalue,proto3" json:"pathvalue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *OpStateResponse) Reset()         { *m = OpStateResponse{} }
func (m *OpStateResponse) String() string { return proto.CompactTextString(m) }
func (*OpStateResponse) ProtoMessage()    {}
func (*OpStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_624d839d9ad9df06, []int{3}
}
func (m *OpStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpStateResponse.Unmarshal(m, b)
}
func (m *OpStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpStateResponse.Marshal(b, m, deterministic)
}
func (m *OpStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpStateResponse.Merge(m, src)
}
func (m *OpStateResponse) XXX_Size() int {
	return xxx_messageInfo_OpStateResponse.Size(m)
}
func (m *OpStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OpStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OpStateResponse proto.InternalMessageInfo

func (m *OpStateResponse) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_NONE
}

func (m *OpStateResponse) GetPathvalue() *change.Value {
	if m != nil {
		return m.Pathvalue
	}
	return nil
}

// Configuration is a descriptor of a submitted configuration change targeted at a single device.
type Configuration struct {
	Name                 string                                                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DeviceID             string                                                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Version              string                                                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	DeviceType           string                                                 `protobuf:"bytes,4,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	Created              *time.Time                                             `protobuf:"bytes,5,opt,name=created,proto3,stdtime" json:"created,omitempty"`
	Updated              *time.Time                                             `protobuf:"bytes,6,opt,name=updated,proto3,stdtime" json:"updated,omitempty"`
	ChangeIDs            []github_com_onosproject_onos_topo_pkg_types_change.ID `protobuf:"bytes,7,rep,name=change_ids,json=changeIds,proto3,casttype=github.com/onosproject/onos-topo/pkg/types/change.ID" json:"change_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                               `json:"-"`
	XXX_unrecognized     []byte                                                 `json:"-"`
	XXX_sizecache        int32                                                  `json:"-"`
}

func (m *Configuration) Reset()         { *m = Configuration{} }
func (m *Configuration) String() string { return proto.CompactTextString(m) }
func (*Configuration) ProtoMessage()    {}
func (*Configuration) Descriptor() ([]byte, []int) {
	return fileDescriptor_624d839d9ad9df06, []int{4}
}
func (m *Configuration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Configuration.Unmarshal(m, b)
}
func (m *Configuration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Configuration.Marshal(b, m, deterministic)
}
func (m *Configuration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Configuration.Merge(m, src)
}
func (m *Configuration) XXX_Size() int {
	return xxx_messageInfo_Configuration.Size(m)
}
func (m *Configuration) XXX_DiscardUnknown() {
	xxx_messageInfo_Configuration.DiscardUnknown(m)
}

var xxx_messageInfo_Configuration proto.InternalMessageInfo

func (m *Configuration) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Configuration) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *Configuration) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Configuration) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *Configuration) GetCreated() *time.Time {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Configuration) GetUpdated() *time.Time {
	if m != nil {
		return m.Updated
	}
	return nil
}

func (m *Configuration) GetChangeIDs() []github_com_onosproject_onos_topo_pkg_types_change.ID {
	if m != nil {
		return m.ChangeIDs
	}
	return nil
}

func init() {
	proto.RegisterEnum("onos.config.diags.Type", Type_name, Type_value)
	proto.RegisterType((*ChangesRequest)(nil), "onos.config.diags.ChangesRequest")
	proto.RegisterType((*ConfigRequest)(nil), "onos.config.diags.ConfigRequest")
	proto.RegisterType((*OpStateRequest)(nil), "onos.config.diags.OpStateRequest")
	proto.RegisterType((*OpStateResponse)(nil), "onos.config.diags.OpStateResponse")
	proto.RegisterType((*Configuration)(nil), "onos.config.diags.Configuration")
}

func init() { proto.RegisterFile("pkg/northbound/diags/diags.proto", fileDescriptor_624d839d9ad9df06) }

var fileDescriptor_624d839d9ad9df06 = []byte{
	// 602 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xad, 0xdb, 0xc4, 0x93, 0x12, 0xd2, 0x15, 0x12, 0xc6, 0x42, 0x72, 0xc8, 0x29, 0x80,
	0xb0, 0xa3, 0x00, 0x42, 0x70, 0xa2, 0xa9, 0x2d, 0x94, 0x4a, 0x6d, 0x90, 0x49, 0x2b, 0x71, 0x42,
	0xfe, 0xd9, 0x3a, 0x86, 0xc6, 0x6b, 0xbc, 0xeb, 0xa0, 0xf2, 0x14, 0xbc, 0x0d, 0x6f, 0x13, 0xa4,
	0x5e, 0x78, 0x07, 0x4e, 0x68, 0x77, 0xed, 0x34, 0xa1, 0xa1, 0xea, 0x85, 0x8b, 0x3d, 0xbb, 0x3b,
	0xf3, 0x7d, 0xf3, 0xf3, 0x0d, 0xb4, 0xb3, 0xcf, 0xb1, 0x9d, 0x92, 0x9c, 0x4d, 0x02, 0x52, 0xa4,
	0x91, 0x1d, 0x25, 0x7e, 0x4c, 0xe5, 0xd7, 0xca, 0x72, 0xc2, 0x08, 0xda, 0x25, 0x29, 0xa1, 0x56,
	0x48, 0xd2, 0xd3, 0x24, 0xb6, 0xc4, 0x83, 0x61, 0xc6, 0x84, 0xc4, 0x67, 0xd8, 0x16, 0x0e, 0x41,
	0x71, 0x6a, 0xb3, 0x64, 0x8a, 0x29, 0xf3, 0xa7, 0x99, 0x8c, 0x31, 0xee, 0xc6, 0x24, 0x26, 0xc2,
	0xb4, 0xb9, 0x55, 0xde, 0xbe, 0x89, 0x13, 0x36, 0x29, 0x02, 0x2b, 0x24, 0x53, 0x9b, 0x83, 0x66,
	0x39, 0xf9, 0x84, 0x43, 0x26, 0xec, 0xa7, 0x92, 0xc0, 0xe6, 0xe9, 0xb0, 0xf3, 0x0c, 0x53, 0x3b,
	0x9c, 0xf8, 0x69, 0x8c, 0xcb, 0x9f, 0x44, 0xe8, 0xcc, 0xa0, 0xb9, 0x2f, 0xce, 0xd4, 0xc3, 0x5f,
	0x0a, 0x4c, 0x19, 0x8a, 0x00, 0xa4, 0xc7, 0xc7, 0x24, 0xa2, 0xba, 0xd2, 0xde, 0xec, 0x6a, 0x03,
	0xf7, 0x62, 0x6e, 0x6a, 0xd2, 0x6f, 0xe8, 0xd0, 0xdf, 0x73, 0xf3, 0xf9, 0x75, 0xc4, 0x8c, 0x64,
	0xe4, 0x0a, 0xad, 0x35, 0x74, 0x3c, 0x4d, 0x9a, 0xc3, 0x88, 0x76, 0xbe, 0xc1, 0xed, 0x7d, 0x91,
	0x5f, 0x45, 0x9b, 0x00, 0x44, 0x78, 0x96, 0x84, 0xcb, 0xb4, 0x07, 0x9c, 0xd6, 0x11, 0xb7, 0x92,
	0xf6, 0xd5, 0x8d, 0x68, 0x97, 0x9b, 0x2f, 0x82, 0x05, 0xb7, 0x34, 0x39, 0xf7, 0x01, 0x34, 0x47,
	0xd9, 0x7b, 0xe6, 0x33, 0x5c, 0x91, 0x1b, 0x50, 0xaf, 0x9e, 0x75, 0xa5, 0xad, 0x74, 0x35, 0x6f,
	0x71, 0x46, 0x0f, 0x40, 0xa3, 0x45, 0x40, 0xc3, 0x3c, 0x09, 0xb0, 0xbe, 0xd1, 0x56, 0xba, 0x75,
	0xef, 0xf2, 0xa2, 0xf3, 0x15, 0xee, 0x2c, 0xb0, 0x68, 0x46, 0x52, 0x8a, 0xd1, 0x13, 0x50, 0x79,
	0xe1, 0x02, 0xa8, 0xd9, 0xbf, 0x67, 0x5d, 0x99, 0xb6, 0x35, 0x3e, 0xcf, 0xb0, 0x27, 0x9c, 0xd0,
	0x4b, 0xd0, 0x32, 0x9f, 0x4d, 0x66, 0xfe, 0x59, 0x21, 0xd1, 0x1b, 0xfd, 0xfb, 0x2b, 0x11, 0x65,
	0xf7, 0x4e, 0xb8, 0x83, 0x77, 0xe9, 0xdb, 0xf9, 0xb5, 0x51, 0x75, 0xb0, 0xc8, 0x7d, 0x96, 0x90,
	0x14, 0x21, 0x50, 0x53, 0x7f, 0x8a, 0xcb, 0x02, 0x84, 0x8d, 0x1e, 0x81, 0xb6, 0xe8, 0xaa, 0x80,
	0xd7, 0x06, 0x3b, 0x17, 0x73, 0xb3, 0x5e, 0x35, 0x75, 0xa9, 0x4e, 0x1d, 0x6a, 0x33, 0x9c, 0xd3,
	0x84, 0xa4, 0xfa, 0xa6, 0x40, 0xa8, 0x8e, 0xc8, 0x84, 0x46, 0x09, 0x22, 0xea, 0x52, 0xc5, 0x6b,
	0x39, 0x2d, 0x5e, 0x0a, 0x7a, 0x0d, 0xb5, 0x30, 0xc7, 0x3e, 0xc3, 0x91, 0xbe, 0x25, 0x4a, 0x30,
	0x2c, 0xa9, 0x67, 0xab, 0xd2, 0xb3, 0x35, 0xae, 0xf4, 0x3c, 0x50, 0xbf, 0xff, 0x34, 0x15, 0xaf,
	0x0a, 0xe0, 0xb1, 0x45, 0x16, 0x89, 0xd8, 0xed, 0x9b, 0xc6, 0x96, 0x01, 0x7f, 0x49, 0xb5, 0xf6,
	0x7f, 0xa4, 0xfa, 0xf8, 0x05, 0xa8, 0xa2, 0xca, 0x3a, 0xa8, 0x47, 0xa3, 0x23, 0xb7, 0x75, 0x0b,
	0x69, 0xb0, 0xb5, 0xe7, 0x38, 0xae, 0xd3, 0x52, 0x50, 0x03, 0x6a, 0xc7, 0xef, 0x9c, 0xbd, 0xb1,
	0xeb, 0xb4, 0x36, 0xf8, 0xc1, 0x73, 0x0f, 0x47, 0x27, 0xae, 0xd3, 0xda, 0xec, 0xff, 0x50, 0xa0,
	0x21, 0x07, 0xe4, 0xf0, 0xa1, 0xa3, 0x43, 0x80, 0xb7, 0x98, 0x95, 0xcb, 0x86, 0x1e, 0xae, 0x91,
	0xc5, 0xea, 0x22, 0x1a, 0xc6, 0x3a, 0x1d, 0x48, 0x9f, 0x9e, 0x82, 0x3e, 0xc0, 0x2e, 0x87, 0x5b,
	0x56, 0x00, 0x45, 0xed, 0x75, 0xa8, 0xcb, 0x6b, 0x66, 0xfc, 0xdb, 0xa3, 0x04, 0xe9, 0x29, 0x7d,
	0x0c, 0x3b, 0xa5, 0xa6, 0x65, 0xe6, 0xc7, 0x22, 0xf3, 0xf2, 0x6a, 0x6d, 0xe6, 0xab, 0xeb, 0x64,
	0x74, 0xae, 0x73, 0x91, 0x5b, 0xd2, 0x53, 0x82, 0x6d, 0x31, 0xe0, 0x67, 0x7f, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xed, 0x91, 0xaa, 0x2d, 0x31, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConfigDiagsClient is the client API for ConfigDiags service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConfigDiagsClient interface {
	// GetChanges returns a stream of submitted changes objects.
	GetChanges(ctx context.Context, in *ChangesRequest, opts ...grpc.CallOption) (ConfigDiags_GetChangesClient, error)
	// GetConfigurations returns a stream of submitted configurations aimed at individual devices.
	GetConfigurations(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (ConfigDiags_GetConfigurationsClient, error)
}

type configDiagsClient struct {
	cc *grpc.ClientConn
}

func NewConfigDiagsClient(cc *grpc.ClientConn) ConfigDiagsClient {
	return &configDiagsClient{cc}
}

func (c *configDiagsClient) GetChanges(ctx context.Context, in *ChangesRequest, opts ...grpc.CallOption) (ConfigDiags_GetChangesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ConfigDiags_serviceDesc.Streams[0], "/onos.config.diags.ConfigDiags/GetChanges", opts...)
	if err != nil {
		return nil, err
	}
	x := &configDiagsGetChangesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ConfigDiags_GetChangesClient interface {
	Recv() (*change.Change, error)
	grpc.ClientStream
}

type configDiagsGetChangesClient struct {
	grpc.ClientStream
}

func (x *configDiagsGetChangesClient) Recv() (*change.Change, error) {
	m := new(change.Change)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *configDiagsClient) GetConfigurations(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (ConfigDiags_GetConfigurationsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ConfigDiags_serviceDesc.Streams[1], "/onos.config.diags.ConfigDiags/GetConfigurations", opts...)
	if err != nil {
		return nil, err
	}
	x := &configDiagsGetConfigurationsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ConfigDiags_GetConfigurationsClient interface {
	Recv() (*Configuration, error)
	grpc.ClientStream
}

type configDiagsGetConfigurationsClient struct {
	grpc.ClientStream
}

func (x *configDiagsGetConfigurationsClient) Recv() (*Configuration, error) {
	m := new(Configuration)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ConfigDiagsServer is the server API for ConfigDiags service.
type ConfigDiagsServer interface {
	// GetChanges returns a stream of submitted changes objects.
	GetChanges(*ChangesRequest, ConfigDiags_GetChangesServer) error
	// GetConfigurations returns a stream of submitted configurations aimed at individual devices.
	GetConfigurations(*ConfigRequest, ConfigDiags_GetConfigurationsServer) error
}

// UnimplementedConfigDiagsServer can be embedded to have forward compatible implementations.
type UnimplementedConfigDiagsServer struct {
}

func (*UnimplementedConfigDiagsServer) GetChanges(req *ChangesRequest, srv ConfigDiags_GetChangesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetChanges not implemented")
}
func (*UnimplementedConfigDiagsServer) GetConfigurations(req *ConfigRequest, srv ConfigDiags_GetConfigurationsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetConfigurations not implemented")
}

func RegisterConfigDiagsServer(s *grpc.Server, srv ConfigDiagsServer) {
	s.RegisterService(&_ConfigDiags_serviceDesc, srv)
}

func _ConfigDiags_GetChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChangesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfigDiagsServer).GetChanges(m, &configDiagsGetChangesServer{stream})
}

type ConfigDiags_GetChangesServer interface {
	Send(*change.Change) error
	grpc.ServerStream
}

type configDiagsGetChangesServer struct {
	grpc.ServerStream
}

func (x *configDiagsGetChangesServer) Send(m *change.Change) error {
	return x.ServerStream.SendMsg(m)
}

func _ConfigDiags_GetConfigurations_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConfigRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfigDiagsServer).GetConfigurations(m, &configDiagsGetConfigurationsServer{stream})
}

type ConfigDiags_GetConfigurationsServer interface {
	Send(*Configuration) error
	grpc.ServerStream
}

type configDiagsGetConfigurationsServer struct {
	grpc.ServerStream
}

func (x *configDiagsGetConfigurationsServer) Send(m *Configuration) error {
	return x.ServerStream.SendMsg(m)
}

var _ConfigDiags_serviceDesc = grpc.ServiceDesc{
	ServiceName: "onos.config.diags.ConfigDiags",
	HandlerType: (*ConfigDiagsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetChanges",
			Handler:       _ConfigDiags_GetChanges_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetConfigurations",
			Handler:       _ConfigDiags_GetConfigurations_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/northbound/diags/diags.proto",
}

// OpStateDiagsClient is the client API for OpStateDiags service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OpStateDiagsClient interface {
	// GetOpState returns a stream of submitted OperationalStateCache aimed at individual devices.
	// If subscribe is true keep on streaming after the initial set are finished
	GetOpState(ctx context.Context, in *OpStateRequest, opts ...grpc.CallOption) (OpStateDiags_GetOpStateClient, error)
}

type opStateDiagsClient struct {
	cc *grpc.ClientConn
}

func NewOpStateDiagsClient(cc *grpc.ClientConn) OpStateDiagsClient {
	return &opStateDiagsClient{cc}
}

func (c *opStateDiagsClient) GetOpState(ctx context.Context, in *OpStateRequest, opts ...grpc.CallOption) (OpStateDiags_GetOpStateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_OpStateDiags_serviceDesc.Streams[0], "/onos.config.diags.OpStateDiags/GetOpState", opts...)
	if err != nil {
		return nil, err
	}
	x := &opStateDiagsGetOpStateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type OpStateDiags_GetOpStateClient interface {
	Recv() (*OpStateResponse, error)
	grpc.ClientStream
}

type opStateDiagsGetOpStateClient struct {
	grpc.ClientStream
}

func (x *opStateDiagsGetOpStateClient) Recv() (*OpStateResponse, error) {
	m := new(OpStateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OpStateDiagsServer is the server API for OpStateDiags service.
type OpStateDiagsServer interface {
	// GetOpState returns a stream of submitted OperationalStateCache aimed at individual devices.
	// If subscribe is true keep on streaming after the initial set are finished
	GetOpState(*OpStateRequest, OpStateDiags_GetOpStateServer) error
}

// UnimplementedOpStateDiagsServer can be embedded to have forward compatible implementations.
type UnimplementedOpStateDiagsServer struct {
}

func (*UnimplementedOpStateDiagsServer) GetOpState(req *OpStateRequest, srv OpStateDiags_GetOpStateServer) error {
	return status.Errorf(codes.Unimplemented, "method GetOpState not implemented")
}

func RegisterOpStateDiagsServer(s *grpc.Server, srv OpStateDiagsServer) {
	s.RegisterService(&_OpStateDiags_serviceDesc, srv)
}

func _OpStateDiags_GetOpState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OpStateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OpStateDiagsServer).GetOpState(m, &opStateDiagsGetOpStateServer{stream})
}

type OpStateDiags_GetOpStateServer interface {
	Send(*OpStateResponse) error
	grpc.ServerStream
}

type opStateDiagsGetOpStateServer struct {
	grpc.ServerStream
}

func (x *opStateDiagsGetOpStateServer) Send(m *OpStateResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _OpStateDiags_serviceDesc = grpc.ServiceDesc{
	ServiceName: "onos.config.diags.OpStateDiags",
	HandlerType: (*OpStateDiagsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetOpState",
			Handler:       _OpStateDiags_GetOpState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/northbound/diags/diags.proto",
}
