nameOverride: ""

replicas: 1

annotations: {}

image:
  repository: onosproject/onos-config
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

resources:
  requests:
    cpu: 0.5
    memory: 512Mi

ingress:
  enabled: false
