linkerd:
  httpPort: 80
  discoveryPortName: http
  image: buoyantio/linkerd:1.4.6
  ingress:
    enabled: false
  name: l5d
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 0
      memory: 512Mi

kubectl:
  image: buoyantio/kubectl:v1.12.2
  resources:
    requests:
      cpu: 0
      memory: 32Mi

prometheus:
  scrape: true
  probe: true
  path: /admin/metrics/prometheus

service:
  type: LoadBalancer

config:
  admin:
    ip: 0.0.0.0
    port: 9990
  namers:
  - kind: io.l5d.k8s
    host: localhost
    port: 8001
  telemetry:
  - kind: io.l5d.prometheus
  - kind: io.l5d.recentRequests
    sampleRate: 0.25
  usage:
    orgId: onos-linkerd
  routers:
  - protocol: h2
    label: outgoing
    dtab: |
      /srv             => /#/io.l5d.k8s/default/grpc;
      /grpc            => /srv;
      /grpc/Northbound => /srv/onos-config-onos-config-manager;
      /svc             => /$/io.buoyant.http.domainToPathPfx/grpc;
    identifier:
      kind: io.l5d.header.path
      segments: 1
    interpreter:
      kind: default
      transformers:
      - kind: io.l5d.k8s.daemonset
        namespace: default
        port: incoming
        service: l5d
    servers:
    - port: 4140
      ip: 0.0.0.0
  - protocol: h2
    label: incoming
    dtab: |
      /srv             => /#/io.l5d.k8s/default/grpc;
      /grpc            => /srv;
      /grpc/Northbound => /srv/onos-config-onos-config-manager;
      /svc             => /$/io.buoyant.http.domainToPathPfx/grpc;
    identifier:
      kind: io.l5d.header.path
      segments: 1
    interpreter:
      kind: default
      transformers:
      - kind: io.l5d.k8s.localnode
    servers:
    - port: 4141
      ip: 0.0.0.0