{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-ingress
spec:
  backend:
    serviceName: {{ template "fullname" . }}
    servicePort: h2
  rules:
    - host: {{ template "fullname" . }}
      http:
        paths:
          - backend:
              serviceName: {{ template "fullname" . }}
              servicePort: h2
{{- end }}